/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,ts}"],
  theme: {
    extend: {
      colors: {
        primary: "var(--mat-sys-primary)",
        "on-primary": "var(--mat-sys-on-primary)",
        surface: "var(--mat-sys-surface)",
        "on-surface": "var(--mat-sys-on-surface)",
        error: "var(--mat-sys-error)",
        "on-error": "var(--mat-sys-on-error)",
        outline: "var(--mat-sys-outline)",
        "primary-container": "var(--mat-sys-primary-container)",
        "on-primary-container": "var(--mat-sys-on-primary-container)",
        secondary: "var(--mat-sys-secondary)",
        "on-secondary": "var(--mat-sys-on-secondary)",
        "secondary-container": "var(--mat-sys-secondary-container)",
        "on-secondary-container": "var(--mat-sys-on-secondary-container)",
        tertiary: "var(--mat-sys-tertiary)",
        "on-tertiary": "var(--mat-sys-on-tertiary)",
        "tertiary-container": "var(--mat-sys-tertiary-container)",
        "on-tertiary-container": "var(--mat-sys-on-tertiary-container)",
        "surface-dim": "var(--mat-sys-surface-dim)",
        "surface-bright": "var(--mat-sys-surface-bright)",
        "surface-container-lowest": "var(--mat-sys-surface-container-lowest)",
        "surface-container-low": "var(--mat-sys-surface-container-low)",
        "surface-container": "var(--mat-sys-surface-container)",
        "surface-container-high": "var(--mat-sys-surface-container-high)",
        "surface-container-highest": "var(--mat-sys-surface-container-highest)",
        "primary-fixed": "var(--mat-sys-primary-fixed)",
        "on-primary-fixed": "var(--mat-sys-on-primary-fixed)",
        "primary-fixed-dim": "var(--mat-sys-primary-fixed-dim)",
        "secondary-fixed": "var(--mat-sys-secondary-fixed)",
        "on-secondary-fixed": "var(--mat-sys-on-secondary-fixed)",
        "secondary-fixed-dim": "var(--mat-sys-secondary-fixed-dim)",
        "tertiary-fixed": "var(--mat-sys-tertiary-fixed)",
        "on-tertiary-fixed": "var(--mat-sys-on-tertiary-fixed)",
        "tertiary-fixed-dim": "var(--mat-sys-tertiary-fixed-dim)",
      },
      boxShadow: {
        level0: "var(--mat-sys-level0)",
        level1: "var(--mat-sys-level1)",
        level2: "var(--mat-sys-level2)",
        level3: "var(--mat-sys-level3)",
        level4: "var(--mat-sys-level4)",
        level5: "var(--mat-sys-level5)",
      },
      fontSize: {
        "body-small": "var(--mat-sys-body-small)",
        "body-medium": "var(--mat-sys-body-medium)",
        "body-large": "var(--mat-sys-body-large)",
        "display-small": "var(--mat-sys-display-small)",
        "display-medium": "var(--mat-sys-display-medium)",
        "display-large": "var(--mat-sys-display-large)",
        "headline-small": "var(--mat-sys-headline-small)",
        "headline-medium": "var(--mat-sys-headline-medium)",
        "headline-large": "var(--mat-sys-headline-large)",
        "label-small": "var(--mat-sys-label-small)",
        "label-medium": "var(--mat-sys-label-medium)",
        "label-large": "var(--mat-sys-label-large)",
        "title-small": "var(--mat-sys-title-small)",
        "title-medium": "var(--mat-sys-title-medium)",
        "title-large": "var(--mat-sys-title-large)",
      },
    },
  },
  plugins: [],
};
